# Generated by Django 5.2 on 2025-04-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_veiculo_acessorio_alter_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(blank=True, related_name='veiculos', to='core.acessorio'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.modelo'),
        ),
    ]
